{% set version = '1.0-8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proj4
  version: {{ version|replace("-", "_") }}

source:
  fn: proj4_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/proj4_{{ version }}.tar.gz
  sha256: 69d3171b3a2baa0dd3d8530d617b5acef0c5b0a261ecd044513af7f8b6a2231b

build:
  merge_build_host: True  # [win]
  number: 1006
  skip: false  # [win]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - proj4

  run:
    - r-base
    - proj4
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('proj4')"  # [not win]
    - "\"%R%\" -e \"library('proj4')\""  # [win]

about:
  home: http://www.rforge.net/proj4/
  license: GPL-2
  summary: A simple interface to lat/long projection and datum transformation of the PROJ.4 cartographic
    projections library. It allows transformation of geographic coordinates from one
    projection and/or datum to another.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
