{% set version = "1.0-14" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-proj4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/proj4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/proj4/proj4_{{ version }}.tar.gz
  sha256: d3d571da92136666dd3658b6006a7d4d4254cdeada5cda21b05b0c0e692a00b6
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ posix }}tar               # [win]
    - {{ posix }}gzip              # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - proj
  run:
    - r-base

test:
  commands:
    - $R -e "library('proj4')"           # [not win]
    - "\"%R%\" -e \"library('proj4')\""  # [win]

about:
  home: http://www.rforge.net/proj4/
  license: GPL-2.0-only
  summary: A simple interface to lat/long projection and datum transformation of the PROJ.4 cartographic projections library. It allows transformation of geographic coordinates from one projection and/or datum to another.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nawendt
    - ocefpaf
    - xylar
