{% set version = '1.0-8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proj4
  version: {{ version|replace("-", "_") }}

source:
  fn: proj4_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/proj4_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/proj4/proj4_{{ version }}.tar.gz
  sha256: 69d3171b3a2baa0dd3d8530d617b5acef0c5b0a261ecd044513af7f8b6a2231b
  patches:
    - win.patch  # [win]

build:
  number: 1008
  merge_build_host: True  # [win]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - proj4

  run:
    - r-base
    - proj4

test:
  commands:
    - $R -e "library('proj4')"  # [not win]
    - "\"%R%\" -e \"library('proj4')\""  # [win]

about:
  home: http://www.rforge.net/proj4/
  license: GPL-2.0
  summary: A simple interface to lat/long projection and datum transformation of the PROJ.4 cartographic
    projections library. It allows transformation of geographic coordinates from one
    projection and/or datum to another.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - nawendt
    - ocefpaf
