appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XjBb6PFX8aZSno+XqP6ig9L7F+wASoUUTXE0tSDYJFYBt3CjJJ6c1REho64VXAQbgf5EDIhc8iXzAWfXhDwMRhQvF0nnbrH6oD2O9rHdoIDt1UNEfrdtAzV6k47sF5SEab5HyPzf99yG3VbUjp8x04exm5pNQBiHKnFGBNDo2kQ3Ni/qUCB8qHg1yOexhPQANe77uow1HNBjRuOB7xY+h6rP6xS0Pb6Clf8Rb6PZpHbOomgauF+P9sp5GSjx5wDZWWs3aiK9isTgkeCxLY7snA7QaIxlq6dCR8Mg3wheGT6Hf4yzgGTyimWlGN90HTYfgBVVdLuzcGfrH0quzCE4reyJ1snRSfhsnKdD3S5B6p82kJFhmKhCBfCWJL+G5REghk6q1JH9NffRybqOhxlLJoicPgBO1Tr04wKxEl8wyTrvRSmgR3NLN8mBhIWvzpzKiE/7gTiiPz4IweKXtOqI6QQnSP1yxIK8WGoFmBSys7RV0rmgOkf++R/RB2sJRwpDL5twg2CQ0DW+0Ec1ARMr+kPOQCm7QbhQOBCDXuH3GWyVRSGLrlfru0jk/rtOgr//kYBwaNnPI/GpKeIA80NZUJyr0uq+LCAWq+cZgAwppO+dNJkzvb1atajMJuqzK7faRiNhVKp+QpyZNSDawDBQ88LRSaMCGmFyDixcUohsD10=
conda_forge_output_validation: true
